- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000 # 5 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Cargo
  wage: 50
  #end-backmen: currency
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FestiveSeason
    prototype: PresentRandom

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    id: SalvagePDA
    ears: ClothingHeadsetCargo
    socks: ClothingUnderwearSocksSalvage
