- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-iaa
  canBeAntag: false
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: LawyerStampProvider
  - !type:GiveItemOnHolidaySpecial
    holiday: FestiveSeason
    prototype: PresentRandom
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLaw
    socks: ClothingUnderwearSockLawyer
  inhand:
    - BriefcaseLawyerFilled
  storage:
    back:
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - HyperLinkBookSOPLaw
