- type: job
  id: TypanBotanist
  name: Ботаник Синдиката
  playTimeTracker: TypanBotanist
  description: Ботаник из далёкого космоса
  startingGear: SyndicateBotanist
  icon: "JobIconTypanBotanist"
  supervisors: job-supervisors-hop
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateBotanist
  equipment:
    ears: ClothingHeadsetAltTypan
    jumpsuit: ClothingUniformJumpsuitTypanBotanist
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesColorBlack
    id: SyndiPDABotan
