- type: job
  id: TypanCargotech
  name: Карготехник Синдиката
  playTimeTracker: TypanCargotech
  description: Грузчик из далёкого космоса
  startingGear: SyndicateCargotech
  icon: "JobIconTypanCargotech"
  supervisors: job-supervisors-qm
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000
    - !type:OverallPlaytimeRequirement
      time: 36000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateCargotech
  equipment:
    ears: ClothingHeadsetAltTypan
    jumpsuit: ClothingUniformJumpsuitTypanCargotech
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsCombatSyndie
    id: TypanIDCardCargo
